### ISSUE TITLE
Which part of the CUDA code corresponds to calculating homodirectional view-space positional gradient?

### ISSUE THREAD

**Issue by JiajieLi7012** [ingra14m/floater-free-gaussian-splatting#2]
Hello, thanks for sharing your excellent work. I'm quite new to the CUDA code and I'm wondering if you could point out to me which part of the CUDA code in `submodules/diff-depth-diff-gaussian-rasterization` you modified to calculate the homodirectional view-space positional gradient in the absGaussian paper? Thanks in advance.

**Comment by charyang-ai** [comment]
@JiajieLi7012  @ingra14m  Hello, good job ! 
I am searching for the modification for 'homodirectional view-space positional gradient ', which is mentioned in paper absgs. 
I think the code should be in backward.cu in submodules/diff-depth-diff-gaussian-rasterization , however, I didn't find it, can you point me the location?
