### ISSUE TITLE
Question for code

### ISSUE THREAD

**Issue by SCUTykLin** [ingra14m/floater-free-gaussian-splatting#3]
Can you briefly tell me what code you changed? 

absgs seems pretty straightforward

Thanks

**Comment by ingra14m** [comment]
Hi, I implemented this mainly based on my observation that the accumulated gradient for each gs has a bug. You can refer to the [rasterization](https://github.com/ingra14m/diff-gaussian-rasterization-extentions/blob/filter-norm/cuda_rasterizer/backward.cu#L549-L551) for more details.

**Comment by SCUTykLin** [comment]
Thanks for your reply.
